apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-volume-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner
      chart: local-static-provisioner
      targetRevision: 2.8.0
      helm:
        valueFiles:
          - $values/local-volume-provisioner/values.yaml
    - repoURL: https://github.com/tombulled/values
      targetRevision: feature/argo-cd # HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: "Source:"
      value: "https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/README.md"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
