apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 7.1.1
      helm:
        valueFiles:
          - $values/minio-tenant/values.yaml
    - repoURL: https://github.com/tombulled/values
      targetRevision: feature/argo-cd # HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: "Source:"
      value: "https://github.com/minio/operator/tree/master/helm/tenant"
    - name: "Docs:"
      value: "https://docs.min.io/community/minio-object-store/reference/tenant-chart-values.html"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
