apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/tombulled/charts
      path: common
      targetRevision: feature/argo-cd # HEAD
      helm:
        valueFiles:
          - $values/postgres/values.yaml
    - repoURL: https://github.com/tombulled/values
      targetRevision: feature/argo-cd # HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
