apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
stringData:
  # TODO: Move these to values file.
  DB_CONNECTION_CHECK_URL: postgres://mattermost:mattermost@postgresql-rw:5432/mattermost?connect_timeout=10
  DB_CONNECTION_STRING: postgres://mattermost:mattermost@postgresql-rw:5432/mattermost?connect_timeout=10
  MM_SQLSETTINGS_DATASOURCEREPLICAS: postgres://mattermost:mattermost@postgresql-rw:5432/mattermost?connect_timeout=10
