{{- range $name, $value := .Values.storageClasses }}
{{- $enabled := ternary .enabled true (ne .enabled nil) }}
{{- $isDefaultClass := ternary .isDefaultClass false (ne .isDefaultClass nil) }}
# {{- $allowVolumeExpansion := ternary .allowVolumeExpansion true (ne .allowVolumeExpansion nil) }}
allowedTopologies: TODO
mountOptions: TODO
parameters: TODO
# {{- $provisioner := .provisioner }}
# {{- $reclaimPolicy := .reclaimPolicy }}
# {{- $volumeBindingMode := .volumeBindingMode }}

{{- if $enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $name | quote }}
  labels: {{- include "common.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .isDefaultClass }}
    storageclass.kubernetes.io/is-default-class: {{ . | quote }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .allowVolumeExpansion }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- end }}
{{- end }}
{{- end }}