apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.mattermost.com
      chart: mattermost-operator
      targetRevision: 1.0.3
      helm:
        valueFiles:
          - $values/mattermost-operator/values.yaml
    - repoURL: https://github.com/tombulled/values
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: "Chart:"
      value: "https://artifacthub.io/packages/helm/mattermost/mattermost-operator"
    - name: "Source:"
      value: "https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-operator"
    - name: "Docs:"
      value: "https://docs.mattermost.com/deploy/server/deploy-kubernetes.html"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
