apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://operator.min.io
      chart: operator
      targetRevision: 7.1.1
      helm:
        valueFiles:
          - $values/minio-operator/values.yaml
    - repoURL: https://github.com/tombulled/values
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: "Source:"
      value: "https://github.com/minio/operator/tree/master/helm/operator"
    - name: "Docs:"
      value: "https://docs.min.io/community/minio-object-store/operations/deployments/k8s-minio-operator.html"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
